### PR TITLE
Sample contracts

### PR DESCRIPTION
**Pull request by naumenkogs**
I updated some examples.

Those are pretty arbitrary because the EIP does not specify how wallets gonna obtain status codes, but rather how they gonna interpret it.

### CODE REVIEW

**Comment by naumenkogs** [comment]
I have no idea why test fails. @expede  could you take a look?

**Comment by expede** [comment]
Looks like the linter is failing. I can clean that up for ya 👌🏻

**Comment by expede** [comment]
Also rebased ☝️

**Review by expede — APPROVED** [review]
Looks good! I made some tweaks and changes. Made the linter pass, tightened a few things up.

Great work 🙌🏻

**Pull request merged**
